# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-14 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('state', models.CharField(choices=[('lagos', 'lagos'), ('others', 'others')], default='Lagos, Nigeria', max_length=100)),
                ('lga1', models.CharField(choices=[('apapa', 'apapa'), ('ajah', 'ajah'), ('bariga', 'bariga'), ('ebute-meta', 'ebute-meta'), ('eti-osa', 'eti-osa'), ('festac', 'festac'), ('gbagada', 'gbagada'), ('ibeju-lekki', 'ibeju-lekki'), ('ifako-ijaye', 'ifako-ijaye'), ('ikeja', 'ikeja'), ('ikorodu', 'ikorodu'), ('ikoyi-obalende', 'ikoyi-obalende'), ('ilupeju', 'ilupeju'), ('ketu', 'ketu'), ('kosofe', 'kosofe'), ('lagos-island', 'lagos-island'), ('lagos-mainland', 'lagos-mainland'), ('magodo', 'magodo'), ('onipanu', 'onipanu'), ('oshodi-isolo', 'oshodi-isolo'), ('somolu', 'somolu'), ('surulere', 'surulere'), ('VI', 'victoria-island')], default='Invalid_lga', max_length=100)),
                ('lga2', models.CharField(choices=[('apapa', 'apapa'), ('ajah', 'ajah'), ('bariga', 'bariga'), ('ebute-meta', 'ebute-meta'), ('eti-osa', 'eti-osa'), ('festac', 'festac'), ('gbagada', 'gbagada'), ('ibeju-lekki', 'ibeju-lekki'), ('ifako-ijaye', 'ifako-ijaye'), ('ikeja', 'ikeja'), ('ikorodu', 'ikorodu'), ('ikoyi-obalende', 'ikoyi-obalende'), ('ilupeju', 'ilupeju'), ('ketu', 'ketu'), ('kosofe', 'kosofe'), ('lagos-island', 'lagos-island'), ('lagos-mainland', 'lagos-mainland'), ('magodo', 'magodo'), ('onipanu', 'onipanu'), ('oshodi-isolo', 'oshodi-isolo'), ('somolu', 'somolu'), ('surulere', 'surulere'), ('VI', 'victoria-island')], default='Invalid_lga', max_length=100)),
                ('lga3', models.CharField(choices=[('apapa', 'apapa'), ('ajah', 'ajah'), ('bariga', 'bariga'), ('ebute-meta', 'ebute-meta'), ('eti-osa', 'eti-osa'), ('festac', 'festac'), ('gbagada', 'gbagada'), ('ibeju-lekki', 'ibeju-lekki'), ('ifako-ijaye', 'ifako-ijaye'), ('ikeja', 'ikeja'), ('ikorodu', 'ikorodu'), ('ikoyi-obalende', 'ikoyi-obalende'), ('ilupeju', 'ilupeju'), ('ketu', 'ketu'), ('kosofe', 'kosofe'), ('lagos-island', 'lagos-island'), ('lagos-mainland', 'lagos-mainland'), ('magodo', 'magodo'), ('onipanu', 'onipanu'), ('oshodi-isolo', 'oshodi-isolo'), ('somolu', 'somolu'), ('surulere', 'surulere'), ('VI', 'victoria-island')], default='Invalid_lga', max_length=100)),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English Language'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Further Mathematics', 'Further Maths'), ('Computer Studies', 'Computer Studies'), ('Technical Drawing', 'Technical Drawing')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Gender', max_length=6)),
                ('middleName', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=100)),
                ('qualification', models.FloatField(default=0)),
                ('recommendation', models.FloatField(default=2.5)),
                ('rating', models.FloatField(default=0.0)),
                ('charge', models.FloatField(default=0.0)),
                ('photo', models.ImageField(upload_to='media/tutors/')),
                ('availability', models.PositiveSmallIntegerField(default=2, verbose_name="Tutor's Availability")),
                ('experience', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
