# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-14 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20170514_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(upload_to='/tutors/'),
        ),
    ]
