# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-15 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20170514_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(upload_to='/tutor/'),
        ),
    ]
