# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_auto_20170520_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
