# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_auto_20170608_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='middleName',
            new_name='middle_name',
        ),
    ]
