# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-13 20:59
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_auto_20170713_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
