# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-13 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_auto_20170713_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(upload_to='media/tutor/'),
        ),
    ]
