# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-13 22:54
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_auto_20170713_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=image_cropping.fields.ImageCropField(upload_to='media/tutor/'),
        ),
    ]
