# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default='middle name', max_length=25),
            preserve_default=False,
        ),
    ]
