# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-10 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170610_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='num_of_times_blacklisted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
