# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-10 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_num_of_times_blacklisted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
