# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-21 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 9, 18, 19, 803650, tzinfo=utc)),
        ),
    ]
