# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-04 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('date_initialized', models.DateField(default=datetime.datetime(2017, 6, 4, 21, 26, 49, 491374, tzinfo=utc), verbose_name='Commencement Date')),
                ('student_id', models.CharField(max_length=10)),
                ('tutor_number', models.CharField(max_length=10)),
                ('total_amount_due', models.FloatField()),
                ('payment_status', models.BooleanField(default=False)),
                ('num_of_days_per_week', models.IntegerField()),
                ('hours_per_day', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('report_tutor', models.BooleanField(default=False)),
                ('blacklist_student', models.BooleanField(default=False)),
                ('tutor_notified', models.BooleanField(default=False)),
                ('student_notified', models.BooleanField(default=False)),
            ],
        ),
    ]
