# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_initialized',
            field=models.DateField(verbose_name='Initialization Date'),
        ),
    ]
