# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-21 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20170608_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_initialized',
            field=models.DateField(default=datetime.datetime(2017, 6, 21, 9, 18, 19, 803650, tzinfo=utc), verbose_name='Initialization Date'),
        ),
    ]
