# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-13 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20170621_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_initialized',
            field=models.DateField(default=datetime.datetime(2017, 7, 13, 20, 38, 51, 833978, tzinfo=utc), verbose_name='Initialization Date'),
        ),
    ]
