# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-03 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20170713_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tutor_bank_account_name',
            field=models.CharField(default='Guaranty Trust Bank (GTB)', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tutor_bank_account_number',
            field=models.CharField(default=None, max_length=10, verbose_name='Tutor NUBAN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='tutor_payment',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
